version: '3.4'

networks:
  ros-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}

services:
  ros-core-service:
    tty: true
    image: multiverseframework/multiverse:demos
    build:
      context: ./images/Multiverse-image/
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO}
    container_name: ros-core-container
    hostname: ros-core
    networks:
      ros-network:
        ipv4_address: ${ROS_IP_CORE}
    environment:
      - ROS_MASTER_URI=http://${ROS_IP_CORE}:11311
      - ROS_IP=${ROS_IP_CORE}
    entrypoint: /entrypoint.bash
    command: roscore

  multiverse-server-service:
    tty: true
    image: multiverseframework/multiverse:demos
    container_name: multiverse-server-container
    hostname: multiverse-server
    networks:
      ros-network:
        ipv4_address: ${ROS_IP_MULTIVERSE_SERVER}
    environment:
      - ROS_MASTER_URI=http://ros-core:11311
      - ROS_IP=${ROS_IP_MULTIVERSE_SERVER}
    volumes:
      - ./images/Multiverse-image/Multiverse/multiverse_ws/src/multiverse_core/multiverse_server:/home/Multiverse/multiverse_ws/src/multiverse_core/multiverse_server:rw
    entrypoint: /entrypoint.bash
    command: sh -c "roslaunch multiverse_server multiverse_server.launch"
    depends_on:
      - ros-core-service

  multiverse-client-mujoco-service:
    tty: true
    image: multiverseframework/multiverse:demos
    container_name: multiverse-client-mujoco-container
    hostname: multiverse-client-mujoco
    networks:
      ros-network:
        ipv4_address: ${ROS_IP_MULTIVERSE_CLIENT_MUJOCO}
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1 #fix some QT bugs
      - HOST_IP=${HOST_IP}
      - ROS_MASTER_URI=http://ros-core:11311
      - ROS_IP=${ROS_IP_MULTIVERSE_CLIENT_MUJOCO}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./images/Multiverse-image/Multiverse/multiverse_ws/src/multiverse_demos:/home/Multiverse/multiverse_ws/src/multiverse_demos:rw
    entrypoint: /entrypoint.bash
    command: sh -c "roslaunch tiago_dual_in_apartment mujoco.launch"
    depends_on:
      - ros-core-service

  multiverse-client-ros-service:
    tty: true
    image: multiverseframework/multiverse:demos
    container_name: multiverse-client-ros-container
    hostname: multiverse-client-ros
    networks:
      ros-network:
        ipv4_address: ${ROS_IP_MULTIVERSE_CLIENT_ROS}
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1 #fix some QT bugs
      - HOST_IP=${HOST_IP}
      - ROS_MASTER_URI=http://ros-core:11311
      - ROS_IP=${ROS_IP_MULTIVERSE_CLIENT_ROS}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./images/Multiverse-image/Multiverse/multiverse_ws/src/multiverse_demos:/home/Multiverse/multiverse_ws/src/multiverse_demos:rw
    entrypoint: /entrypoint.bash
    command: sh -c "roslaunch tiago_dual_in_apartment multiverse_client.launch"
    depends_on:
      - ros-core-service