version: '3.4'

networks:
  ros-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}

services:
  ros-core-service:
    tty: true
    image: ros:${ROS_DISTRO}-ros-core
    container_name: ros-core-container
    hostname: ros-core
    networks:
      ros-network:
        ipv4_address: ${ROS_IP_CORE}
    environment:
      - ROS_MASTER_URI=http://${ROS_IP_CORE}:11311
      - ROS_IP=${ROS_IP_CORE}
    command: roscore

  multiverse-server-service:
    tty: true
    image: multiverseframework/multiverse:iros-2023
    build:
      context: ./images/Multiverse-image/
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO}
    container_name: multiverse-server-container
    hostname: multiverse-server
    networks:
      ros-network:
        ipv4_address: ${ROS_IP_MULTIVERSE_SERVER}
    entrypoint: multiverse_server

  multiverse-client-mujoco-service:
    tty: true
    image: multiverseframework/multiverse-demos:iros-2023
    build:
      context: ./images/MultiverseDemos-image/
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO}
    container_name: multiverse-client-mujoco-container
    hostname: multiverse-client-mujoco
    networks:
      ros-network:
        ipv4_address: ${ROS_IP_MULTIVERSE_CLIENT_MUJOCO}
    environment:
      - ROS_MASTER_URI=http://ros-core:11311
      - ROS_IP=${ROS_IP_MULTIVERSE_CLIENT_MUJOCO}
    volumes:
      - ./images/MultiverseDemos-image/multiverse_objects:/home/Multiverse/multiverse_ws/src/multiverse_objects:rw
      - ./images/MultiverseDemos-image/multiverse_robots:/home/Multiverse/multiverse_ws/src/multiverse_robots:rw
      - ./images/MultiverseDemos-image/multiverse_world:/home/Multiverse/multiverse_ws/src/multiverse_world:rw
      - ./images/MultiverseDemos-image/multiverse_demos:/home/Multiverse/multiverse_ws/src/multiverse_demos:rw
    entrypoint: /entrypoint.bash
    command: sh -c "roslaunch tiago_dual_in_apartment mujoco.launch headless:=true server_host:=tcp://${ROS_IP_MULTIVERSE_SERVER}"
    depends_on:
      - ros-core-service
      - multiverse-server-service

  multiverse-client-ros-service:
    tty: true
    image: multiverseframework/multiverse-demos:iros-2023
    container_name: multiverse-client-ros-container
    hostname: multiverse-client-ros
    networks:
      ros-network:
        ipv4_address: ${ROS_IP_MULTIVERSE_CLIENT_ROS}
    environment:
      - ROS_MASTER_URI=http://ros-core:11311
      - ROS_IP=${ROS_IP_MULTIVERSE_CLIENT_ROS}
    volumes:
      - ./images/MultiverseDemos-image/multiverse_objects:/home/Multiverse/multiverse_ws/src/multiverse_objects:rw
      - ./images/MultiverseDemos-image/multiverse_robots:/home/Multiverse/multiverse_ws/src/multiverse_robots:rw
      - ./images/MultiverseDemos-image/multiverse_world:/home/Multiverse/multiverse_ws/src/multiverse_world:rw
      - ./images/MultiverseDemos-image/multiverse_demos:/home/Multiverse/multiverse_ws/src/multiverse_demos:rw
    entrypoint: /entrypoint.bash
    command: sh -c "roslaunch tiago_dual_in_apartment multiverse_socket.launch server_host:=tcp://${ROS_IP_MULTIVERSE_SERVER}"
    depends_on:
      - ros-core-service
      - multiverse-server-service

  giskard-service:
    tty: true
    image: multiverseframework/giskard:iros-2023
    build:
      context: ./images/Giskard-image/
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO}
    container_name: giskard-container
    hostname: giskard
    networks:
      ros-network:
        ipv4_address: ${ROS_IP_GISKARD}
    environment:
      - ROS_MASTER_URI=http://ros-core:11311
      - ROS_IP=${ROS_IP_GISKARD}
    volumes:
      - ./images/MultiverseDemos-image/multiverse_robots:/home/Multiverse/multiverse_ws/src/multiverse_robots:rw
      - ./images/Giskard-image/giskard_msgs:/home/Multiverse/giskard_ws/src/giskard_msgs:rw
      - ./images/Giskard-image/giskardpy:/home/Multiverse/giskard_ws/src/giskardpy:rw
    entrypoint: /entrypoint.bash
    command: sh -c "roslaunch tiago_dual_control tiago_dual_giskard.launch"
    depends_on:
      - multiverse-client-mujoco-service
      - multiverse-client-ros-service

  rviz-service:
    tty: true
    image: multiverseframework/giskard:iros-2023
    container_name: rviz-container
    hostname: rviz
    networks:
      ros-network:
        ipv4_address: ${ROS_IP_RVIZ}
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1 #fix some QT bugs
      - ROS_MASTER_URI=http://ros-core:11311
      - ROS_IP=${ROS_IP_RVIZ}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./images/Giskard-image/giskard_msgs:/home/Multiverse/giskard_ws/src/giskard_msgs:rw
      - ./images/Giskard-image/giskardpy:/home/Multiverse/giskard_ws/src/giskardpy:rw
      - ./images/MultiverseDemos-image/multiverse_objects:/home/Multiverse/multiverse_ws/src/multiverse_objects:rw
      - ./images/MultiverseDemos-image/multiverse_robots:/home/Multiverse/multiverse_ws/src/multiverse_robots:rw
      - ./images/MultiverseDemos-image/multiverse_world:/home/Multiverse/multiverse_ws/src/multiverse_world:rw
      - ./images/MultiverseDemos-image/multiverse_demos:/home/Multiverse/multiverse_ws/src/multiverse_demos:rw
    entrypoint: /entrypoint.bash
    command: sh -c "roslaunch tiago_dual_in_apartment rviz.launch"
    depends_on:
      - multiverse-client-ros-service