version: '3.4'

networks:
  ros-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}

services:
  multiverse-service:
    tty: true
    image: multiverseframework/multiverse:ubuntu-20.04
    build:
      context: ./images/Multiverse-image/
      dockerfile: Dockerfile
    container_name: multiverse-container