version: '3.4'
services:
  binderhub:
    image: multiversedocker:binderhub
    build:
      context: ../
      dockerfile: ./binder/Dockerfile
    tty: true
    stdin_open: true
    entrypoint:  ["/home/binder/entrypoint.sh"]
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0
    # command: xvfb-run jupyter lab --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0
    # user: root
    # working_dir: /home
    ports:
      - 8888:8888
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/home/binder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]